/**
 * Insights Validator
 *
 * Validates insights generated for a job ID
 * Checks structure, data integrity, and database persistence
 *
 * Usage:
 *   npx ts-node --require tsconfig-paths/register tests/insights-validator.test.ts <jobId>
 *   npx ts-node --require tsconfig-paths/register tests/insights-validator.test.ts 84fc8019-59cd-4b4a-8127-3be3d5b6e184
 */

import "dotenv/config";
import { initializePrisma } from "@/config/db";
import { insightValidators } from "@/validators/insight.validator";

interface ValidationReport {
  jobId: string;
  totalInsights: number;
  validInsights: number;
  invalidInsights: Array<{
    id: string;
    type: string;
    errors: string[];
  }>;
  insights: Array<{
    id: string;
    type: string;
    severity: string;
    hasData: boolean;
    dataValid: boolean;
    referenceCount: number;
  }>;
}

/**
 * Validate all insights for a job
 */
async function validateInsights(jobId: string): Promise<ValidationReport> {
  console.log("\n" + "=".repeat(80));
  console.log("[INSIGHTS VALIDATOR] Starting insights validation");
  console.log(`[INSIGHTS VALIDATOR] Job ID: ${jobId}`);
  console.log("=".repeat(80) + "\n");

  try {
    // Initialize database
    const prisma = await initializePrisma();
    await prisma.$connect();

    // Fetch all insights for the job
    const insights = await prisma.insights.findMany({
      where: { job_id: jobId },
      orderBy: { created_at: "asc" },
    });

    console.log(`[INSIGHTS VALIDATOR] Found ${insights.length} insights\n`);

    if (insights.length === 0) {
      console.log("⚠️  No insights found for this job");
      await prisma.$disconnect();
      return {
        jobId,
        totalInsights: 0,
        validInsights: 0,
        invalidInsights: [],
        insights: [],
      };
    }

    // Validate each insight
    const invalidInsights: ValidationReport["invalidInsights"] = [];
    const validatedInsights: ValidationReport["insights"] = [];

    console.log("━".repeat(80));
    console.log("INSIGHT VALIDATION DETAILS");
    console.log("━".repeat(80) + "\n");

    for (const insight of insights) {
      const hasData = !!insight.data;
      let dataValid = false;
      let validationErrors: string[] = [];

      // Validate insight data
      if (hasData) {
        const validation = insightValidators.validateInsightData(
          insight.insight_type,
          insight.data,
        );
        dataValid = validation.valid;

        if (!validation.valid) {
          validationErrors = validation.errors?.map((e: any) =>
            typeof e === "string" ? e : e.message || "Unknown error",
          ) || ["Validation failed"];
        }
      } else {
        validationErrors.push("Missing data payload");
      }

      const findingRefs = Array.isArray(insight.finding_references)
        ? insight.finding_references.length
        : 0;
      const logRefs = Array.isArray(insight.log_references)
        ? insight.log_references.length
        : 0;

      const insightInfo = {
        id: insight.id,
        type: insight.insight_type,
        severity: insight.severity || "UNKNOWN",
        hasData,
        dataValid,
        referenceCount: findingRefs + logRefs,
      };

      validatedInsights.push(insightInfo);

      // Display result
      const statusIcon = dataValid ? "✅" : "❌";
      console.log(
        `${statusIcon} ${insight.insight_type} (${insight.severity})`,
      );
      console.log(`   ID: ${insight.id}`);
      console.log(`   Generated by: ${insight.generated_by}`);
      console.log(`   Has Data: ${hasData}`);
      console.log(`   Data Valid: ${dataValid}`);
      console.log(`   References: ${findingRefs} findings, ${logRefs} logs`);

      if (validationErrors.length > 0) {
        console.log(`   Errors:`);
        validationErrors.forEach((err) => {
          console.log(`     • ${err}`);
        });
        invalidInsights.push({
          id: insight.id,
          type: insight.insight_type,
          errors: validationErrors,
        });
      }

      console.log();
    }

    // Summary
    const validCount = insights.length - invalidInsights.length;

    console.log("━".repeat(80));
    console.log("VALIDATION SUMMARY");
    console.log("━".repeat(80));
    console.log(`Total Insights: ${insights.length}`);
    console.log(`✅ Valid: ${validCount}`);
    console.log(`❌ Invalid: ${invalidInsights.length}`);

    if (invalidInsights.length === 0) {
      console.log("\n🎉 All insights are valid!");
    } else {
      console.log("\n⚠️  Some insights have validation errors");
    }

    console.log("=".repeat(80) + "\n");

    await prisma.$disconnect();

    return {
      jobId,
      totalInsights: insights.length,
      validInsights: validCount,
      invalidInsights,
      insights: validatedInsights,
    };
  } catch (error) {
    console.error(`\n❌ Validation error: ${error}`);
    if (error instanceof Error) {
      console.error(`Stack: ${error.stack}`);
    }
    throw error;
  }
}

/**
 * Main entry point
 */
async function main() {
  const jobId = process.argv[2];

  if (!jobId) {
    console.error(
      "Usage: npx ts-node tests/insights-validator.test.ts <jobId>",
    );
    console.error(
      "Example: npx ts-node tests/insights-validator.test.ts 84fc8019-59cd-4b4a-8127-3be3d5b6e184",
    );
    process.exit(1);
  }

  try {
    const report = await validateInsights(jobId);

    // Exit with appropriate code
    process.exit(report.invalidInsights.length === 0 ? 0 : 1);
  } catch (error) {
    console.error("Fatal error:", error);
    process.exit(1);
  }
}

main();
