/**
 * Insights Generation Test Utility
 *
 * Tests insights generation for a given job ID
 * Verifies both deterministic and LLM insights are generated correctly
 *
 * Usage:
 *   npx ts-node --require tsconfig-paths/register tests/insights-generator.test.ts <jobId>
 *   npx ts-node --require tsconfig-paths/register tests/insights-generator.test.ts 84fc8019-59cd-4b4a-8127-3be3d5b6e184
 */

import "dotenv/config";
import { initializePrisma } from "@/config/db";
import { insightsOrchestrator } from "@/services/insights/insights.orchestrator";
import logger from "@/config/logger";

interface TestResult {
  success: boolean;
  jobId: string;
  deterministicInsights: number;
  llmInsights: number;
  totalInsights: number;
  failedInsights: Array<{ type: string; reason: string }>;
  executionTimeMs: number;
  errors?: string[];
}

/**
 * Test insights generation for a job
 */
async function testInsightsGeneration(jobId: string): Promise<TestResult> {
  console.log("\n" + "=".repeat(80));
  console.log("[INSIGHTS TEST] Starting insights generation test");
  console.log(`[INSIGHTS TEST] Job ID: ${jobId}`);
  console.log("=".repeat(80) + "\n");

  const startTime = Date.now();
  const errors: string[] = [];

  try {
    // Initialize database
    console.log("[INSIGHTS TEST] Initializing database...");
    const prisma = await initializePrisma();
    await prisma.$connect();
    console.log("✅ Database connected\n");

    // Verify job exists
    console.log("[INSIGHTS TEST] Verifying job exists...");
    const job = await prisma.jobs.findUnique({
      where: { id: jobId },
      include: {
        analyzer_findings: true,
        insights: true,
      },
    });

    if (!job) {
      const errorMsg = `Job ${jobId} not found`;
      console.error(`❌ ${errorMsg}`);
      errors.push(errorMsg);
      return {
        success: false,
        jobId,
        deterministicInsights: 0,
        llmInsights: 0,
        totalInsights: 0,
        failedInsights: [],
        executionTimeMs: Date.now() - startTime,
        errors,
      };
    }

    console.log(`✅ Job found: ${job.file_name}`);
    console.log(`   Status: ${job.status}`);
    console.log(`   Stage: ${job.last_completed_stage}`);
    console.log(`   Analyzer Findings: ${job.analyzer_findings.length}`);
    console.log(`   Existing Insights: ${job.insights.length}\n`);

    // Verify job has analyzer findings
    if (job.analyzer_findings.length === 0) {
      const errorMsg = `No analyzer findings found for job ${jobId}. Run analyzer first.`;
      console.warn(`⚠️  ${errorMsg}`);
      errors.push(errorMsg);
    }

    // Generate insights
    console.log(
      "[INSIGHTS TEST] Calling insightsOrchestrator.generateCompleteInsights()...\n",
    );
    const result = await insightsOrchestrator.generateCompleteInsights(jobId);

    // Log results
    console.log("[INSIGHTS TEST] ✅ Insights generation completed\n");
    console.log("━".repeat(80));
    console.log("RESULTS SUMMARY");
    console.log("━".repeat(80));
    console.log(
      `Deterministic Insights: ${result.deterministic_insights.length}`,
    );
    result.deterministic_insights.forEach((insight) => {
      console.log(`  • ${insight.insight_type} (${insight.severity})`);
    });

    console.log(`\nLLM Insights: ${result.llm_insights.length}`);
    result.llm_insights.forEach((insight) => {
      console.log(`  • ${insight.insight_type} (${insight.severity})`);
    });

    console.log(`\nTotal Insights Generated: ${result.total_insights}`);
    console.log(`Execution Time: ${result.executionTimeMs}ms`);

    if (result.failed_insights.length > 0) {
      console.log(`\n⚠️  Failed Insights: ${result.failed_insights.length}`);
      result.failed_insights.forEach((failed) => {
        console.log(`  • ${failed.type}: ${failed.reason}`);
      });
    }

    console.log("\n" + "━".repeat(80));
    console.log("DATABASE PERSISTENCE CHECK");
    console.log("━".repeat(80));

    // Verify insights were persisted to database
    const persistedInsights = await prisma.insights.findMany({
      where: { job_id: jobId },
    });

    console.log(`Insights in Database: ${persistedInsights.length}`);
    persistedInsights.forEach((insight) => {
      console.log(
        `  • ${insight.insight_type} - Generated by: ${insight.generated_by}`,
      );
    });

    console.log("\n" + "=".repeat(80));
    console.log("TEST RESULT");
    console.log("=".repeat(80));

    const testResult: TestResult = {
      success: result.total_insights > 0,
      jobId,
      deterministicInsights: result.deterministic_insights.length,
      llmInsights: result.llm_insights.length,
      totalInsights: result.total_insights,
      failedInsights: result.failed_insights,
      executionTimeMs: result.executionTimeMs,
      errors: errors.length > 0 ? errors : undefined,
    };

    if (testResult.success) {
      console.log(`✅ SUCCESS: Generated ${result.total_insights} insights`);
    } else {
      console.log(`❌ FAILED: No insights were generated`);
    }

    if (persistedInsights.length === result.total_insights) {
      console.log(
        `✅ PERSISTENCE: All insights persisted to database (${persistedInsights.length} records)`,
      );
    } else {
      console.log(
        `⚠️  PERSISTENCE: Mismatch - Generated ${result.total_insights}, Found ${persistedInsights.length} in DB`,
      );
    }

    console.log("=".repeat(80) + "\n");

    await prisma.$disconnect();

    return testResult;
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    console.error(`\n❌ Error: ${errorMsg}`);
    if (error instanceof Error) {
      console.error(`Stack: ${error.stack}`);
    }

    return {
      success: false,
      jobId,
      deterministicInsights: 0,
      llmInsights: 0,
      totalInsights: 0,
      failedInsights: [],
      executionTimeMs: Date.now() - startTime,
      errors: [...errors, errorMsg],
    };
  }
}

/**
 * Main entry point
 */
async function main() {
  // Get job ID from command line arguments
  const jobId = process.argv[2];

  if (!jobId) {
    console.error(
      "Usage: npx ts-node tests/insights-generator.test.ts <jobId>",
    );
    console.error(
      "Example: npx ts-node tests/insights-generator.test.ts 84fc8019-59cd-4b4a-8127-3be3d5b6e184",
    );
    process.exit(1);
  }

  try {
    const result = await testInsightsGeneration(jobId);

    // Exit with appropriate code
    process.exit(result.success ? 0 : 1);
  } catch (error) {
    console.error("Fatal error:", error);
    process.exit(1);
  }
}

main();
